# Auto-generated Bash function wrappers from ~/.bashrc.d
# Do not edit this file manually.

function link_dotfiles
  bash -c 'source "/home/snens_arch/.bashrc.d/link_dotfiles.sh"; link_dotfiles "$@"' -- $argv
end

function configuration_enviroment
  bash -c 'source "/home/snens_arch/.bashrc.d/utilities.sh"; configuration_enviroment "$@"' -- $argv
end

function ctee
  bash -c 'source "/home/snens_arch/.bashrc.d/utilities.sh"; ctee "$@"' -- $argv
end

function hilf
  bash -c 'source "/home/snens_arch/.bashrc.d/utilities.sh"; hilf "$@"' -- $argv
end

function hman
  bash -c 'source "/home/snens_arch/.bashrc.d/utilities.sh"; hman "$@"' -- $argv
end

function see
  bash -c 'source "/home/snens_arch/.bashrc.d/utilities.sh"; see "$@"' -- $argv
end

function tee_clipboard
  bash -c 'source "/home/snens_arch/.bashrc.d/utilities.sh"; tee_clipboard "$@"' -- $argv
end

function generate_fish_wrappers
  bash -c 'source "/home/snens_arch/.bashrc.d/generate_fish_wrappers.sh"; generate_fish_wrappers "$@"' -- $argv
end

function manage_symlinks
  bash -c 'source "/home/snens_arch/.bashrc.d/manage_symlinks.sh"; manage_symlinks "$@"' -- $argv
end

function reinstall_symlinks
  bash -c 'source "/home/snens_arch/.bashrc.d/reinstall_symlinks.sh"; reinstall_symlinks "$@"' -- $argv
end

