#!/bin/bash

source "$HOME"/.bashrc

MOUNT_PATH="MOUNT_PATH"
REMOTE_ADDRESS="REMOTE_ADDRESS"
REMOTE_SSH_CONNECTION="REMOTE_SSH_CONNECTION"

mount_sftp $MOUNT_PATH $REMOTE_SSH_CONNECTION $REMOTE_ADDRESS
