# Auto-generated Bash function wrappers from ~/.bashrc.d
# Do not edit this file manually.

function link_dotfiles
  bash -c 'source "/home/snens_arch/.bashrc.d/link_dotfiles.sh"; link_dotfiles "$@"' -- $argv
end

function generate_fish_wrappers
  bash -c 'source "/home/snens_arch/.bashrc.d/generate_fish_wrappers.sh"; generate_fish_wrappers "$@"' -- $argv
end

function manage_symlinks
  bash -c 'source "/home/snens_arch/.bashrc.d/manage_symlinks.sh"; manage_symlinks "$@"' -- $argv
end

function reinstall_symlinks
  bash -c 'source "/home/snens_arch/.bashrc.d/reinstall_symlinks.sh"; reinstall_symlinks "$@"' -- $argv
end

function compress
  bash -c 'source "/home/snens_arch/.bashrc.d/functions.sh"; compress "$@"' -- $argv
end

function configuration_enviroment
  bash -c 'source "/home/snens_arch/.bashrc.d/functions.sh"; configuration_enviroment "$@"' -- $argv
end

function ctee
  bash -c 'source "/home/snens_arch/.bashrc.d/functions.sh"; ctee "$@"' -- $argv
end

function hilf
  bash -c 'source "/home/snens_arch/.bashrc.d/functions.sh"; hilf "$@"' -- $argv
end

function hman
  bash -c 'source "/home/snens_arch/.bashrc.d/functions.sh"; hman "$@"' -- $argv
end

function iso2sd
  bash -c 'source "/home/snens_arch/.bashrc.d/functions.sh"; iso2sd "$@"' -- $argv
end

function see
  bash -c 'source "/home/snens_arch/.bashrc.d/functions.sh"; see "$@"' -- $argv
end

function startvm_services
  bash -c 'source "/home/snens_arch/.bashrc.d/functions.sh"; startvm_services "$@"' -- $argv
end

function stopvm_services
  bash -c 'source "/home/snens_arch/.bashrc.d/functions.sh"; stopvm_services "$@"' -- $argv
end

function tee_clipboard
  bash -c 'source "/home/snens_arch/.bashrc.d/functions.sh"; tee_clipboard "$@"' -- $argv
end

function web2app
  bash -c 'source "/home/snens_arch/.bashrc.d/functions.sh"; web2app "$@"' -- $argv
end

function web2app_remove
  bash -c 'source "/home/snens_arch/.bashrc.d/functions.sh"; web2app_remove "$@"' -- $argv
end

