# Auto-generated Bash function wrappers from ~/.bashrc.d
# Do not edit this file manually.

function bash_config_export_bash_to_fish
  bash -c '. "/home/snens_arch/.bashrc.d.logout/export_bash_to_fish.sh";'
end

