# Auto-generated Bash function wrappers from ~/.bashrc.d
# Do not edit this file manually.

function bash_config_symlink_config
  bash -c '. "/home/snens_arch/.bashrc.d.login/symlink_config.sh";'
end

function bash_config_create_reinstall_symlinks
  bash -c '. "/home/snens_arch/.bashrc.d.login/create_reinstall_symlinks.sh";'
end

